{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "busted.fullname" . }}
  labels:
    {{- include "busted.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "busted.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
{{- end }}
