[package]
name = "busted-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
aya = { version = "0.13", optional = true, default-features = false }

[features]
default = []
user = ["aya"]

[lib]
path = "src/lib.rs"
